### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sfragkos** [QijingZheng/VaspBandUnfolding#1]
Hello Qijing,

I tried to install your code but i didnt make it.
What I want to do, is to plot the wavefunctions in real space.
Could you please make me the instructions more clear?
Thank you sincerely!

Sotirios Fragkos

**Comment by sfragkos** [comment]
I think i managed to install it, but know i get the following error
 print 'Calculating IPR of #spin %4d, #kpt %4d, #band %4d' % (ispin+1, ikpt+1, iband+1)
                                                            ^
SyntaxError: invalid syntax

**Comment by QijingZheng** [comment]
Hi Sotirios

The error says something about the syntax, it may be that you are using
python3 to run the script, which could be a problem since I was using
python2 when I wrote the script.

Maybe you can avoid this error by explicitly using python2, e.g. python2
xxx.py

Best
Qijing

**Comment by sfragkos** [comment]
Thank you very much for your answer.
Your code works fine when i tried it on your example. But when i try to apply it in my case, i get the following error:
>>> **phi = wav.wfc_r(ikpt=1, iband=72, ngrid=wav._ngrid * 2)**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dimoulas/.local/lib/python2.7/site-packages/vaspwfc.py", line 258, in wfc_r
    gvec = self.gvectors(ikpt)
  File "/home/dimoulas/.local/lib/python2.7/site-packages/vaspwfc.py", line 195, in gvectors
    (Gvec.shape[0], self._nplws[ikpt -1], np.prod(self._ngrid))
**AssertionError: No. of planewaves not consistent! 6821 13642 17595**

Do you know how can i fix this? what is ngrid? and what should be my KPOINTS file format?
Thanks again!!!

**Comment by QijingZheng** [comment]
Hi Sotirios

Is your WAVECAR obtained from an Gamma-only VASP? Because the error message
indicates that the number of G-vectors and planewaves does not match.

The ngrid determines the grid size out the FFT.

Best
Qijing

**Comment by sfragkos** [comment]
Hi Qijing
Because I'm new in DFT and i dont understand much yet, I attach you my INCAR KPOINTS and POSCAR files. I used 2 different types of KPOINTS file as you will see. What their format should be?
I tried to turn off SOC, and this error didnt appear this time, but when i used **wav.save2vesta(phi, poscar='/my_dir_to_/POSCAR')** the wfc_i.vasp wfc_r.vasp file didn't appear (but it work for your example).

Thanks for your patient!

**Comment by sfragkos** [comment]
**system = MoTe2**
ISTART = 0
ICHARG = 1
LCHARG = .TRUE.

ENCUT = 450
ISMEAR = 0
SIGMA = 0.1
POTIM = 0.5
ISYM = 2
#ISPIN = 2

NSW = 0
ISIF = 2
EDIFF = 1E-6
EDIFFG = -0.001
IBRION = -1

#LWAVE = .TRUE.
LORBIT = 0
LNONCOLLINEAR = .TRUE.
LSORBIT = .TRUE.

LPLANE = .TRUE.
NPAR = 4
NSIM = 4

**KPOINTS v1**
kmesh
0
Monkhorst Pack
12 10 6
0 0 0

**KPOINTS v2**
kmesh
1
reciprocal
0 0 0 6.

**Comment by QijingZheng** [comment]
Hi Sotirios

The error does not complain about the KPOINTS format.

From your INCAR and KPOINTS V1, I guess you are doing a calculation for
bulk 1T'-MoTe2?
If so, then KPOINTS v1 is appropriate for the calculation, maybe you can
increase the size of the k-grid.

According to your INCAR, you are doing a calculation with spin-orbit
coupling, which, unfortunately, was not taken into account in the wfc_r
function in my code.
So there will be no "*.vasp" output by the code.

Best
Qijing

**Comment by sfragkos** [comment]
Ok Qijing thank you very much!
One last question. If i want to plot the wavefuntions at the Γ point, what **ikpt** should be equal to?

**Comment by sfragkos** [comment]
Thanks for everything! need any citation for using your code?

**Comment by QijingZheng** [comment]
It is not mandatory, but I am glad if you could cite my code so that more people will know it and it may help them with their problems.

**Comment by sfragkos** [comment]
Ok, how should I write the citation?
I have also one more question, the fact that SOC wasnt included in these calculations, what effect could have to the way the wavefunctions look? ( the calculations were actually for Td-MoTe2 at Γ point and not for 1T' )

**Comment by QijingZheng** [comment]
I don't know, maybe just a link to the code is ok...

By including SOC in VASP calculations, the wavefunctions then become a spinor \phi -> (\phi^+, \phi^-), i.e. a two-component function.  Note that I add a plus/minus sign in the superscript, however  , there are no spin up/down for a spinor.

Check these sites for more information:
https://github.com/rubel75/fold2Bloch-VASP
http://www.andrew.cmu.edu/user/feenstra/wavetrans/

**Comment by Subhendupj** [comment]
Another question: The "WAVECAR" used for transition dipole moment (TDM) calcualtion should be taken from "scf" calculation or from "band" calculation? I want to calculate the  TDM for a particular "K " point (not at Gamma). So the KPOINT value I should give from the OUTCAR of my band calculation. Thats why my doubt is which WAVECAR I should use?

**Comment by QijingZheng** [comment]
Hi

- I think I convert the TDM in Debye, but I am not so sure about the conversion. Anyway, one usually concerns the relative intensity of the TDM.

- Either WAVECAR is OK, depending on which k-point you are interested in.

Best
Qijing
