### ISSUE TITLE
How to cite this repository

### ISSUE THREAD

**Issue by yifengwucms** [QijingZheng/VaspBandUnfolding#16]
Dear Professor Zheng,

Thanks for this excellent work!
Could you please add a citation option to this repository so I can cite your work in my publications?

Best,
Yifeng

**Comment by QijingZheng** [comment]
Hi Yifeng

Sorry for the late reply. 

A way to cite this repository can be found in this paper: PHYS. REV. X 11, 041030 (2021)

"Q. Zheng, Vasp band unfolding, retrieved from https://github.com/QijingZheng/VaspBandUnfolding"

Best
Qijing
