### ISSUE TITLE
No module named 'pysbt'

### ISSUE THREAD

**Issue by byunghoETRI** [QijingZheng/VaspBandUnfolding#19]
Hello.
When I run aewfc.py, I got the ModuleNotFoundError: No module named 'pysbt'.
- traceback---->
  File "/root/vasp_6.1.0/gitClone/VaspBandUnfolding/All-electron-wavefunction-in-real-space.py", line 2, in <module>
    from aewfc import vasp_ae_wfc
  File "/root/vasp_6.1.0/gitClone/VaspBandUnfolding/aewfc.py", line 5, in <module>
    from pysbt import pysbt
ModuleNotFoundError: No module named 'pysbt'

How can I handle this error?
thanks...

**Comment by QijingZheng** [comment]
Please install the pySBT (https://github.com/QijingZheng/pySBT) package.

I noted that you were using vasp 6.1.0, which I have not tested myself, therefore there might be unexpected problems.

For the underlying formulation of aewfc, please refer to this post: http://staff.ustc.edu.cn/~zqj/posts/VASP-All-Electron-WFC/

**Comment by byunghoETRI** [comment]
Thans for your fast replay.Regards,Chung.2022. 10. 17. 오전 10:49에 郑奇靖 ***@***.***>님이 작성:
Please install the pySBT (https://github.com/QijingZheng/pySBT) package.
I noted that you were using vasp 6.1.0, which I have not tested myself, therefore there might be unexpected problems.
For the underlying formulation of aewfc, please refer to this post: http://staff.ustc.edu.cn/~zqj/posts/VASP-All-Electron-WFC/
