### ISSUE TITLE
Raw data

### ISSUE THREAD

**Issue by MNovotny2** [QijingZheng/VaspBandUnfolding#26]
Dear Prof. Qijing Zheng,
I'm having problems extracting the unfolded  band energies in data form. After printing the spectral function after unfolding I'm still getting the folded bands. Could you please either direct me to the correct variables or add a function that also outputs the band structure in data form.
Thank you very much.

**Comment by QijingZheng** [comment]
Hi

- Please make sure that you have followed the correct procedure. In principle, you should get a png figure with the unfolded band.

- I have added an function to export the raw data, please update your local repo and reinstalled the scripts. You can export the as follows:

```python
....
xx = unfold(xxxxx)
sw = xx.spectral_weight(kpoits) 
xx.write(sw, kpoints, cell)
```

You should get a text file named 'unfolding_weight.dat', where the three columns correspond to: k-coordinates, energies, weights.

You can easily plot the band using gnuplot

```bash
plot 'unfolding_weight.dat' u 1:2:3 w p ps variable
```
